name: run examples

on:
  push
  # workflow_dispatch:

jobs:
  install:
    uses: kima-org/run-examples/.github/workflows/reusable.yml@main

  run-example:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          python -c "import kima"