name: run examples

on:
  push
  # workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

  run-example:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          python -c "import kima"
          