name: run examples

on:
  push
  # workflow_dispatch

jobs:
  - uses: kima-org/run-examples/.github/workflows/reusable.yml@main

  _51Peg:
    runs-on: ubuntu-latest
    steps:
      
      - name: Run 51Peg example
        run : |
          python -c "from kima import examples; examples._51Peg(run=True, load=True, steps=10_000)"
