name: run examples

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 1,3,5"

jobs:
  _51Peg:
    runs-on: ubuntu-latest
    steps:
      - uses: kima-org/run-examples/reusable.yml@main
      
      - name: Run 51Peg example
        run : |
          python -c "from kima import examples; examples._51Peg(run=True, load=True, steps=10_000)"
