name: run examples

on:
  push:
  workflow_dispatch:

jobs:
  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kima-org/run-examples/.github/actions/install.yml@main

      - name: test
        run: |
          python -c "import kima"
