name: run examples

on:
  push
  # workflow_dispatch:

jobs:
  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: kima-org/run-examples/.github/workflows/reusable.yml@main
      - name: test
        run: |
          python -c "import kima"
