name: run examples

on:
  push:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: test import
        run: |
          python -c "import kima"

  run-examples:
    strategy:
      matrix:
        example:
          - _51Peg
          - multi_instruments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: run example
        run: |
          python -c "from kima.examples import ${{ matrix.example }}; ${{ matrix.example }}(run=True, load=True)"

  # run-51Peg:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10'
  #         cache: 'pip' # caching pip dependencies
  #     - run: pip install -r requirements.txt

  #     - name: run example
  #       run: |
  #         python -c "from kima.examples import _51Peg; _51Peg(run=True, load=True)"